from pathlib import Path
from PIL import Image,ImageOps
import zipfile,io,json,html,re
from detail_content import enrich
from finish_content import finish
R=Path(__file__).parent; D=R/'dist'; A=D/'assets'; U=Path('/workspace/scratch/ce8dae64492a/upload'); A.mkdir(parents=True,exist_ok=True)
products=[('ca-chem','Cá chẽm','Barramundi','BARAMUNDI','khac',0),('muc-xa-den','Mực xà đen','Black Squid','BLACK SQUID','muc',5),('ca-ngu-o','Cá ngừ ồ','Bullet Tuna','BULLET TUNA','ngu',0),('ca-ngu-hoa','Cá ngừ hoa','Eastern Little Tuna','EASTERN LITTLE TUNA','ngu',0),('ca-chim-den','Cá chim đen','Black Pomfret','CÁ BLACK POMFRET','khac',0),('ca-nuc-hgt','Cá nục gai cắt đầu','HGT','CÁ HGT','nuc',0),('ca-liet-chi-vang','Cá liệt chỉ vàng','Striped Pony Fish','CÁ LIỆT','khac',0),('ca-banh-lai-trang','Cá bánh lái trắng','Moon Fish','CÁ MOON','khac',0),('ca-trao-mat-to','Cá tráo mắt to','Bigeye Scad','CÁ TRÁO','nuc',1),('ca-song','Cá sòng','Horse Mackerel','HORSE','nuc',0),('ca-bac-ma','Cá bạc má','Indian Mackerel','INDIAN','nuc',0),('ca-nuc-suon','Cá nục suôn / cá nục dài','Layang Scad','LAYANG','nuc',0),('ca-nuc-duoi-do','Cá nục đuôi đỏ','Redtail Scad','REDTAIL','nuc',0),('ca-nuc-tron','Cá nục tròn / cá nục gai','Round Scad','ROUND','nuc',0),('ca-ro-phi','Cá rô phi','Tilapia','TILAPIA','khac',0),('ca-ngan-duoi-vang','Cá ngân đuôi vàng','Yellow Tail','YELLOW TAIL','khac',0),('ca-ngu-vay-vang','Cá ngừ vây vàng','Yellowfin Tuna','YELLOWDISH','ngu',0)]
def extract(prefix,slug,first=0,limit=3):
 existing=[A/f'{slug}-{j}.webp' for j in range(limit)]
 if all(p.exists() for p in existing):return ['/assets/'+p.name for p in existing]
 z=next(U.glob(prefix+'*1).zip')); result=[]
 with zipfile.ZipFile(z) as f:
  names=[n for n in f.namelist() if n.lower().endswith(('.jpg','.png','.jpeg'))]
  order=[first]+[i for i in range(len(names)) if i!=first]
  for j,i in enumerate(order[:limit]):
   p=A/f'{slug}-{j}.webp'; im=ImageOps.exif_transpose(Image.open(io.BytesIO(f.read(names[i])))).convert('RGB'); im.thumbnail((1400,1400));im.save(p,'WEBP',quality=84);result.append('/assets/'+p.name)
 return result
pdata=[]
for slug,name,en,prefix,group,idx in products:
 pdata.append(dict(slug=slug,name=name,en=en,group=group,images=extract(prefix,slug,idx)))
# Extra product photos supplied later (already optimised in dist/assets).
extra_photos={'ca-bac-ma':[3,4,5,6,8,10,11,12],'ca-ngan-duoi-vang':range(3,22),'muc-xa-den':range(3,11),'ca-ngu-hoa':range(3,5)}
for p in pdata:
 for j in extra_photos.get(p['slug'],[]):
  if (A/f"{p['slug']}-{j}.webp").exists():p['images'].append(f"/assets/{p['slug']}-{j}.webp")
for prefix,slug,idx,limit in [('XƯỞNG','xuong',3,4),('HÀNG THÀNH','kho',1,3),('HÀNG CÔNG','dong-hang',8,4),('HỘI CHỢ','hoi-cho',2,5)]:extract(prefix,slug,idx,limit)
if not (A/'logo.png').exists():Image.open('/workspace/scratch/ce8dae64492a/original_logo/image.png').save(A/'logo.png')
(R/'products.json').write_text(json.dumps(pdata,ensure_ascii=False,indent=2))
E=html.escape
nav=[('/','Trang chủ'),('/gioi-thieu/','Giới thiệu'),('/san-pham/','Sản phẩm'),('/thuong-mai-xnk/','Thương mại & XNK'),('/nang-luc/','Năng lực'),('/hoat-dong/','Hoạt động'),('/kien-thuc/','Kiến thức')]
def img(src,alt,cls='',eager=False):return f'<img src="{src}" alt="{E(alt)}" class="{cls}" loading="{"eager" if eager else "lazy"}" decoding="async">'
def btn(url,label,cls=''):return f'<a class="button {cls}" href="{url}">{label}</a>'
def figure(src,label):return f'<figure><button class="image-button" data-photo="{src}" data-caption="{E(label)}" aria-label="Xem ảnh lớn: {E(label)}">{img(src,label)}</button><figcaption>{label}</figcaption></figure>'
def icon(name):
 paths={
 'pin':'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="3"/>',
 'phone':'<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.79 19.79 0 0 1 2.12 4.2 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.12.96.36 1.9.7 2.79a2 2 0 0 1-.45 2.11L8.09 9.89a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.89.34 1.83.58 2.79.7A2 2 0 0 1 22 16.92Z"/>',
 'mail':'<rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 6-10 7L2 6"/>',
 'grid':'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
 'layers':'<path d="m12 3 10 5-10 5L2 8l10-5ZM2 12l10 5 10-5M2 16l10 5 10-5"/>',
 'send':'<path d="m22 2-7 20-4-9-9-4 20-7ZM22 2 11 13"/>'}
 return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">'+paths[name]+'</svg>'

def page(path,title,body,desc=None):
 body=finish(path,title,enrich(path,title,body,pdata),pdata,icon)
 active=''.join(f'<a href="{url}" {"aria-current=page" if path==url or (url!="/" and path.startswith(url)) else ""}>{label}</a>' for url,label in nav)
 h=f'''<!doctype html><html lang="vi"{' data-page="home"' if path=="/" else ''}><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><script src="/assets/intro-gate.js"></script><title>{E(title)} | MAI KỲ HÀ</title><meta name="description" content="{E(desc or 'MAI KỲ HÀ — Kết nối đại dương, phủ sóng toàn cầu. Thương mại và xuất nhập khẩu thủy sản tại Đà Nẵng. Khám phá sản phẩm và cơ hội hợp tác.')}"><link rel="icon" type="image/png" href="/assets/favicon.png"><link rel="apple-touch-icon" href="/assets/favicon.png"><link rel="stylesheet" href="/assets/style.css"><script defer src="/assets/app.js"></script></head><body><a class="skip" href="#main">Đến nội dung</a><header><div class="header-wrap"><a class="brand" href="/"><span class="logo-shine">{img('/assets/logo.png','Logo MAI KỲ HÀ',eager=True)}</span><span>MAI KỲ HÀ SEAFOOD</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu ☰</button><nav id="navigation" aria-label="Điều hướng chính">{active}{btn('/lien-he/','Liên hệ')}</nav></div></header><main id="main">{body}</main><footer><div class="wrap footer-grid"><div class="footer-brand"><a class="footer-logo" href="/" aria-label="MAI KỲ HÀ — Trang chủ"><span class="logo-shine">{img('/assets/logo.png','Logo MAI KỲ HÀ')}</span></a><div><a class="brand-name" href="/">MAI KỲ HÀ</a><p class="footer-slogan">Kết nối đại dương,<br>phủ sóng toàn cầu</p><p>Thương mại và xuất nhập khẩu thủy sản</p></div></div><address class="footer-contact"><a class="contact-row" href="https://share.google/FtUZWLp4R0nZVjGmS" target="_blank" rel="noopener" aria-label="Xem địa chỉ trên Google Maps"><span class="contact-icon">{icon('pin')}</span><span>452 Phạm Văn Đồng, Xã Núi Thành,<br>Thành phố Đà Nẵng</span></a><a class="contact-row" href="tel:+842353565568"><span class="contact-icon">{icon('phone')}</span><span>0235 356 5568</span></a><a class="contact-row" href="mailto:maikyhaseafood01@gmail.com"><span class="contact-icon">{icon('mail')}</span><span>maikyhaseafood01@gmail.com</span></a></address><div class="footer-links"><a href="/san-pham/">{icon('grid')}<span>Danh mục sản phẩm</span></a><a href="/nang-luc/">{icon('layers')}<span>Năng lực thực tế</span></a><a href="/lien-he/">{icon('send')}<span>Gửi yêu cầu hợp tác</span></a></div></div><div class="wrap copyright">© MAI KỲ HÀ · Thủy sản Việt Nam</div></footer><dialog class="lightbox" aria-label="Thư viện hình ảnh" aria-describedby="gallery-caption"><button class="close" aria-label="Đóng ảnh">×</button><img alt=""><p id="gallery-caption" aria-live="polite"></p><div class="gallery-controls"><button type="button" data-gallery-prev>Ảnh trước</button><span class="gallery-position" aria-live="polite"></span><button type="button" data-gallery-next>Ảnh tiếp</button></div></dialog></body></html>'''
 # Reserve intrinsic image space to prevent layout shifts and premature reveals.
 def dimensions(match):
  tag=match.group(0); src=re.search(r'src="(/assets/[^"?]+)"',tag)
  if src and 'width=' not in tag:
   asset=D/src.group(1).lstrip('/')
   if asset.exists():
    with Image.open(asset) as picture:w,h=picture.size
    return tag[:-1]+f' width="{w}" height="{h}">'
  return tag
 h=re.sub(r'<img\b[^>]*>',dimensions,h)
 # Product images: wrap for hover zoom, red frame and a "view details" button.
 h=re.sub(r'(<a class="(?:product-card|mosaic-item)[^"]*"[^>]*>)(<img\b[^>]*>)',r'\1<span class="card-media">\2<em class="view-detail">Xem chi tiết</em></span>',h)
 target=D/path.strip('/')/'index.html' if path!='/' else D/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(h)
def intro(kicker,title,description):return f'<section class="page-intro sea"><div class="wrap"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="lead">{description}</p></div></section>'
def cta():return '<section class="cta"><div class="wrap"><div><p class="eyebrow">KẾT NỐI ĐẠI DƯƠNG, PHỦ SÓNG TOÀN CẦU</p><h2>Cùng kết nối cơ hội thủy sản</h2><p>Chia sẻ mặt hàng, quy cách và thị trường bạn hướng đến để cùng trao đổi phương án hợp tác.</p></div>'+btn('/lien-he/','Gửi yêu cầu thủy sản')+'</div></section>'
def card(p):return f'<a class="product-card" href="/san-pham/{p["slug"]}/" data-group="{p["group"]}" data-name="{E(p["name"])}">{img(p["images"][0],p["name"])}<div><h3>{p["name"]}</h3><p>{p["en"]}</p><span>Xem sản phẩm →</span></div></a>'
by={p['slug']:p for p in pdata}
# Homepage hero slideshow: (image, alt text, caption, dot label), in story order.
hero_images=[('ca-chem-0','Sản phẩm cá chẽm thực tế','SẢN PHẨM THỦY SẢN','Xem sản phẩm thủy sản'),('ca-ngu-vay-vang-0','Cá ngừ vây vàng thực tế','CÁ NGỪ VÂY VÀNG','Xem cá ngừ vây vàng'),('muc-xa-den-0','Mực xà đen thực tế','MỰC XÀ ĐEN','Xem mực xà đen'),('xuong-0','Khu vực xử lý sản phẩm','XỬ LÝ SẢN PHẨM','Xem khu vực xử lý'),('kho-0','Hàng thành phẩm trong kho','BẢO QUẢN THÀNH PHẨM','Xem kho thành phẩm'),('dong-hang-0','Lô hàng chuẩn bị xuất xưởng','CHUẨN BỊ XUẤT XƯỞNG','Xem hàng xuất xưởng'),('dong-hang-1','Container lạnh vận chuyển hàng','CONTAINER LẠNH','Xem container vận chuyển'),('hoi-cho-3','Gặp gỡ đối tác tại hội chợ','KẾT NỐI TẠI HỘI CHỢ','Xem hoạt động hội chợ')]
hero_slides=''.join(f'<figure class="hero-slide{" is-active" if i==0 else ""}" aria-hidden="{str(i!=0).lower()}">{img(f"/assets/{src}.webp",alt,eager=i==0)}<figcaption>{cap}</figcaption></figure>' for i,(src,alt,cap,_) in enumerate(hero_images))
hero_dots=''.join(f'<button aria-label="{label}" aria-pressed="{str(i==0).lower()}" data-slide="{i}"></button>' for i,(_,_,_,label) in enumerate(hero_images))
hero=f'''<section class="hero sea"><div class="wrap hero-grid"><div class="hero-copy"><p class="eyebrow">MAI KỲ HÀ SEAFOOD / VIETNAM</p><h1 class="brand-slogan-hero">Kết nối đại dương,<br><span>phủ sóng toàn cầu</span></h1><p class="lead">Kết nối nguồn hàng thủy sản Việt Nam với nhu cầu của đối tác, hướng đến những cơ hội hợp tác trên thị trường quốc tế.</p>{btn('/san-pham/','Khám phá sản phẩm')}</div><div class="hero-visual" role="region" aria-label="Hình ảnh hoạt động thực tế"><div class="hero-photo">{hero_slides}</div><div class="hero-stamp">MAI KỲ HÀ SEAFOOD<span>VIETNAM</span></div><div class="hero-controls" hidden><div class="hero-dots" aria-label="Chọn hình ảnh">{hero_dots}</div></div></div></div></section><div class="red-rail"><div class="wrap"><span>HÌNH ẢNH HÀNG HÓA THỰC TẾ</span><span>ĐÀ NẴNG · VIỆT NAM</span></div></div>'''
mosaic=''.join(f'<a class="mosaic-item item-{i}" href="/san-pham/{slug}/">{img(by[slug]["images"][0],by[slug]["name"])}<span>{by[slug]["name"]}<b>↗</b></span></a>' for i,slug in enumerate(['ca-ngu-o','ca-nuc-suon','muc-xa-den','ca-bac-ma']))
body=hero+f'<section class="section products-home"><div class="wrap"><p class="eyebrow">SẢN PHẨM</p><h2>Các dòng sản phẩm – hình ảnh thực tế</h2><p class="sub">Khám phá các mặt hàng thủy sản MAI KỲ HÀ đang tiếp nhận giao dịch.</p><div class="mosaic">{mosaic}</div><a class="text-link" href="/san-pham/">Xem toàn bộ danh mục →</a></div></section>'
body+=f'''<section class="section capability sea"><div class="wrap split"><div><p class="eyebrow">NĂNG LỰC THỰC TẾ</p><h2>HÀNG HÓA ĐƯỢC<br>CHUẨN BỊ QUA<br>TỪNG CÔNG ĐOẠN</h2><p>Hình ảnh xưởng xử lý, kho thành phẩm và lô hàng chuẩn bị giao cho đối tác.</p><div class="process-line">XỬ LÝ · LƯU KHO · ĐÓNG HÀNG</div><a class="text-link light" href="/nang-luc/">Tìm hiểu năng lực →</a></div><div class="process-photos">{figure('/assets/xuong-0.webp','Khu vực xử lý sản phẩm')}{figure('/assets/kho-0.webp','Hàng thành phẩm trong kho')}{figure('/assets/dong-hang-0.webp','Chuẩn bị giao hàng')}</div></div></section><section class="event-strip event-feature"><div class="wrap event-feature-grid"><div class="event-copy"><h2>Gặp gỡ đối tác tại triển lãm</h2><p>Hình ảnh hoạt động thực tế của MAI KỲ HÀ.</p>{btn('/hoat-dong/hoi-cho/','Xem hoạt động','outline')}</div><div class="event-slides" data-slides role="region" aria-label="Hình ảnh tại THAIFEX – Anuga Asia">'''+''.join(f'<figure class="event-slide{" is-active" if i==0 else ""}" aria-hidden="{str(i!=0).lower()}">{img(src,alt,eager=i==0)}</figure>' for i,(src,alt) in enumerate([('/assets/hoi-cho-0.webp','Gặp gỡ tại hội chợ ngành thủy sản'),('/assets/hoi-cho-4.webp','Hình ảnh tại THAIFEX – Anuga Asia'),('/assets/hoi-cho-1.webp','Hoạt động kết nối tại hội chợ')]))+'<div class="event-dots" aria-label="Chọn hình ảnh">'+''.join(f'<button type="button" aria-label="Ảnh {i+1}" aria-pressed="{str(i==0).lower()}" data-slide-to="{i}"></button>' for i in range(3))+'''</div></div></div></section>'''
page('/','Thương mại và xuất nhập khẩu thủy sản',body)
page('/gioi-thieu/','Giới thiệu',intro('VỀ CHÚNG TÔI','MAI KỲ HÀ','Kết nối đại dương, phủ sóng toàn cầu — định hướng của MAI KỲ HÀ trong thương mại và xuất nhập khẩu thủy sản từ Đà Nẵng.')+'''<section class="section"><div class="wrap split"><div><h2>Trao đổi rõ ràng,<br>hợp tác theo nhu cầu thực tế</h2><p>MAI KỲ HÀ tiếp nhận nhu cầu mua bán thủy sản theo từng mặt hàng, quy cách, khối lượng và điều kiện giao dịch. Chúng tôi làm rõ những thông tin cần thiết để trao đổi phương án phù hợp với từng đối tác.</p><p>Danh mục gồm các dòng cá ngừ, cá nục, cá bạc má, cá sòng, các loại cá khác và mực xà đen.</p><a class="text-link" href="/san-pham/">Tìm hiểu danh mục sản phẩm →</a></div>'''+figure('/assets/hoi-cho-4.webp','Hoạt động kết nối tại hội chợ')+'''</div></section><section class="section pale"><div class="wrap"><h2>Cách chúng tôi làm việc</h2><div class="three"><article><h3>Hiểu đúng nhu cầu</h3><p>Làm rõ mặt hàng, quy cách và các yêu cầu quan trọng trước khi trao đổi phương án.</p></article><article><h3>Thống nhất điều kiện</h3><p>Trao đổi thông tin sản phẩm, khối lượng, đóng gói và điều kiện giao nhận.</p></article><article><h3>Phối hợp thực hiện</h3><p>Giữ đầu mối trao đổi trong quá trình triển khai giao dịch.</p></article></div></div></section>'''+cta())
filters='<div class="filters" aria-label="Lọc sản phẩm">'+''.join(f'<button data-filter="{k}" aria-pressed="{str(k=="all").lower()}">{v}</button>' for k,v in [('all','Tất cả'),('ngu','Cá ngừ'),('nuc','Cá nục, bạc má & cá sòng'),('khac','Các loại cá khác'),('muc','Mực')])+'</div>'
page('/san-pham/','Sản phẩm',intro('DANH MỤC','Các dòng sản phẩm – hình ảnh thực tế','Lựa chọn mặt hàng và gửi thông tin để xác nhận quy cách, khối lượng cùng khả năng cung ứng tại thời điểm giao dịch.')+'<section class="section"><div class="wrap"><h2 class="sr-only">Danh mục sản phẩm</h2>'+filters+'<div class="product-grid">'+''.join(map(card,pdata))+'</div></div></section>'+cta())
for p in pdata:
 name=p['name']; slug=p['slug']; special='Sản phẩm cá nục gai cắt đầu được giới thiệu cho nhu cầu nguyên liệu đóng hộp. Quy cách xử lý chi tiết cần được thống nhất theo đơn hàng.' if slug=='ca-nuc-hgt' else f'MAI KỲ HÀ tiếp nhận yêu cầu giao dịch {name.lower()} theo quy cách, khối lượng và điều kiện cụ thể.'
 rows=''.join(f'<tr><th scope="row">{a}</th><td>{b}</td></tr>' for a,b in [('Sản phẩm',name),('Dạng hàng & xử lý','Trao đổi theo yêu cầu đơn hàng'),('Kích cỡ & đóng gói','Xác nhận khi hỏi hàng'),('Khối lượng','Theo nhu cầu và khả năng cung ứng'),('Nguồn gốc & chứng từ','Xác nhận theo lô hàng'),('Điều kiện bảo quản','Trao đổi theo dạng sản phẩm')])
 page(f'/san-pham/{slug}/',name,intro('SẢN PHẨM',name,special)+f'<section class="section"><div class="wrap"><a class="back" href="/san-pham/">← Danh mục sản phẩm</a><div class="detail-grid"><div class="gallery">'+''.join(figure(src,name+' — hình ảnh thực tế') for src in p['images'])+f'</div><div class="detail-info"><h2>Thông tin hỏi hàng</h2><table>{rows}</table><p>Cho chúng tôi biết quy cách, khối lượng, địa điểm giao và thời gian cần hàng để trao đổi cụ thể.</p>'+btn('/lien-he/?san-pham='+slug,'Hỏi về sản phẩm này')+'</div></div></div></section>')
page('/thuong-mai-xnk/','Thương mại & xuất nhập khẩu',intro('HỢP TÁC KINH DOANH','Thương mại & xuất nhập khẩu thủy sản','Tiếp nhận nhu cầu mua hàng, giới thiệu nguồn cung và hợp tác theo từng thị trường, từng đơn hàng.')+'''<section class="section"><div class="wrap two"><article class="panel"><h2>Dành cho bên mua</h2><p>Gửi tên hàng, quy cách, khối lượng, địa điểm giao và thời gian dự kiến để MAI KỲ HÀ xem xét, trao đổi phương án.</p>'''+btn('/lien-he/?nhu-cau=mua','Gửi nhu cầu mua')+'''</article><article class="panel"><h2>Dành cho bên cung ứng</h2><p>Giới thiệu mặt hàng, nguồn gốc, khả năng cung ứng và hồ sơ doanh nghiệp để trao đổi mức độ phù hợp.</p>'''+btn('/lien-he/?nhu-cau=cung-ung','Giới thiệu nguồn hàng')+'''</article></div></section><section class="section pale"><div class="wrap"><h2>Từ yêu cầu đến phương án giao dịch</h2><ol class="steps"><li><h3>Gửi nhu cầu</h3><p>Thông tin sản phẩm, khối lượng và điểm giao.</p></li><li><h3>Làm rõ quy cách</h3><p>Yêu cầu xử lý, chất lượng, đóng gói và chứng từ.</p></li><li><h3>Thống nhất điều kiện</h3><p>Báo giá, lịch thực hiện và trách nhiệm của mỗi bên.</p></li><li><h3>Phối hợp triển khai</h3><p>Thực hiện theo các nội dung đã thống nhất.</p></li></ol></div></section>'''+cta())
cap=intro('NĂNG LỰC','Từ xử lý đến chuẩn bị giao hàng','Tìm hiểu hoạt động thực tế qua hình ảnh khu vực xử lý, lưu kho thành phẩm và đóng hàng.')
# Stress that every capability photo is real and unedited.
cap=cap.replace('</p></div></section>','</p><p class="real-badge"><span aria-hidden="true">✓</span>100% HÌNH ẢNH THỰC TẾ · KHÔNG QUA CHỈNH SỬA</p></div></section>',1)
cap+='<section class="section real-note-section"><div class="wrap"><div class="real-note"><span class="real-note-icon" aria-hidden="true">✓</span><div><h2>Hình ảnh thực tế, không qua chỉnh sửa</h2><p>Toàn bộ hình ảnh trên trang này được chụp trực tiếp tại khu xử lý, kho thành phẩm và khi đóng hàng. Hình ảnh giữ nguyên hiện trạng, không qua chỉnh sửa hay dàn dựng.</p></div></div></div></section>'
for i,(slug,title,copy) in enumerate([('xuong','Xử lý và chuẩn bị sản phẩm','Hình ảnh các công đoạn xử lý, phân loại và chuẩn bị hàng thủy sản theo quy cách.'),('kho','Lưu kho thành phẩm','Hình ảnh thành phẩm được sắp xếp trong khu vực lưu kho trước khi giao hàng.'),('dong-hang','Đóng hàng và giao nhận','Hình ảnh thùng thành phẩm được đóng xếp vào container theo kế hoạch giao hàng.')]):
 videos=''
 if slug=='xuong':
  clips=[('xuong-1','Video thực tế: phân loại và xử lý cá tại xưởng'),('xuong-2','Video thực tế: sơ chế, phân loại và vận chuyển nguyên liệu trong xưởng')]
  videos='<div class="video-grid">'+''.join(f'<figure class="video-card"><video controls playsinline preload="none" poster="/assets/video/{v}.webp" aria-label="{cap}"><source src="/assets/video/{v}.mp4" type="video/mp4"></video><figcaption>{cap}</figcaption></figure>' for v,cap in clips)+'</div>'
 cap+=f'<section class="section {"pale" if i%2 else ""}"><div class="wrap"><div class="section-heading"><h2>{title}</h2><p>{copy}</p></div><div class="three photo-grid">'+''.join(figure(f'/assets/{slug}-{j}.webp',title) for j in range(3))+'</div>'+videos+'</div></section>'
page('/nang-luc/','Năng lực',cap+cta())
page('/hoat-dong/','Hoạt động thực tế',intro('HOẠT ĐỘNG','Hình ảnh từ công việc thực tế','Sản phẩm, lô hàng và các hoạt động kết nối của MAI KỲ HÀ.')+'<section class="section"><div class="wrap two"><a class="story" href="/hoat-dong/hoi-cho/">'+img('/assets/hoi-cho-0.webp','Hội chợ ngành thủy sản')+'<h2>MAI KỲ HÀ tại THAIFEX – Anuga Asia</h2><p>Gặp gỡ và trao đổi tại các gian hàng.</p></a><a class="story" href="/nang-luc/">'+img('/assets/dong-hang-0.webp','Hàng đóng vào container')+'<h2>Chuẩn bị đơn hàng thủy sản</h2><p>Từ xử lý, lưu kho đến đóng hàng.</p></a></div></section>')
page('/hoat-dong/hoi-cho/','Tham gia hội chợ',intro('KẾT NỐI ĐỐI TÁC','MAI KỲ HÀ tại THAIFEX – Anuga Asia','Hình ảnh công ty tham gia triển lãm và gặp gỡ các đơn vị trong ngành.')+'<section class="section"><div class="wrap"><p class="prose">Thông qua các hoạt động tại hội chợ, MAI KỲ HÀ có cơ hội tìm hiểu sản phẩm, tiếp xúc với doanh nghiệp và trao đổi nhu cầu hợp tác trong lĩnh vực thủy sản.</p><div class="three photo-grid">'+''.join(figure(f'/assets/hoi-cho-{i}.webp','Hình ảnh tại THAIFEX – Anuga Asia') for i in range(5))+'</div></div></section>'+cta())
articles=[('hoi-hang','Cần chuẩn bị gì khi hỏi mua thủy sản?', [('Xác định mặt hàng','Ghi tên sản phẩm và dạng hàng mong muốn. Có thể gửi ảnh tham khảo để làm rõ yêu cầu.'),('Mô tả quy cách','Nêu kích cỡ, cách xử lý, đóng gói và những tiêu chí quan trọng với đơn hàng của bạn.'),('Khối lượng và lịch giao','Cho biết sản lượng dự kiến, nhu cầu một lần hay định kỳ, điểm giao và thời gian cần hàng.'),('Thông tin liên hệ','Cung cấp tên doanh nghiệp, người phụ trách và email hoặc số điện thoại để thuận tiện trao đổi.')]),('quy-cach','Làm rõ quy cách và đóng gói khi hỏi hàng',[('Dạng sản phẩm','Xác định hàng nguyên con hay đã xử lý và các yêu cầu cụ thể. Tên mặt hàng chưa thể hiện đầy đủ quy cách.'),('Kích cỡ và đơn vị','Ghi rõ đơn vị tính cho kích cỡ, khối lượng và số lượng để tránh cách hiểu khác nhau.'),('Bao bì','Trao đổi khối lượng mỗi kiện, cách đóng gói, nhãn và thông tin cần thể hiện.'),('Xác nhận trước khi chốt','Đối chiếu thông tin báo giá với yêu cầu đã gửi trước khi thống nhất đơn hàng.')]),('dieu-kien-giao-dich','Những nội dung cần thống nhất trước khi giao dịch',[('Thông tin hàng hóa','Thống nhất mặt hàng, quy cách, khối lượng và yêu cầu chất lượng cho đơn hàng cụ thể.'),('Giá và thanh toán','Làm rõ giá áp dụng, phạm vi chi phí, thời hạn và phương thức thanh toán.'),('Lịch và điểm giao','Xác nhận thời gian, địa điểm, điều kiện giao nhận và đầu mối phối hợp.'),('Hồ sơ đi kèm','Trao đổi các chứng từ cần thiết cho lô hàng và thị trường dự kiến trước khi thực hiện.')])]
page('/kien-thuc/','Kiến thức',intro('THÔNG TIN HỮU ÍCH','Chuẩn bị tốt cho lần trao đổi đầu tiên','Các hướng dẫn ngắn giúp bạn mô tả nhu cầu mua bán thủy sản rõ ràng hơn.')+'<section class="section"><div class="wrap three">'+''.join(f'<a class="panel article-card" href="/kien-thuc/{slug}/"><span class="eyebrow">HƯỚNG DẪN HỎI HÀNG</span><h2>{title}</h2><span class="text-link">Đọc bài →</span></a>' for slug,title,_ in articles)+'</div></section>')
for slug,title,parts in articles:page('/kien-thuc/'+slug+'/',title,intro('KIẾN THỨC',title,'Hướng dẫn chuẩn bị thông tin khi trao đổi với MAI KỲ HÀ.')+'<article class="section prose wrap">'+''.join(f'<h2>{h}</h2><p>{p}</p>' for h,p in parts)+'</article>'+cta())
options=''.join(f'<option value="{p["slug"]}">{p["name"]}</option>' for p in pdata)
page('/lien-he/','Liên hệ',intro('LIÊN HỆ','Trao đổi nhu cầu thủy sản','Gửi thông tin về mặt hàng hoặc cơ hội hợp tác để MAI KỲ HÀ trao đổi cùng bạn.')+f'''<section class="section"><div class="wrap contact-grid"><aside><h2>MAI KỲ HÀ</h2><p>452 Phạm Văn Đồng, Xã Núi Thành,<br>Thành phố Đà Nẵng</p><a class="contact-large" href="tel:+842353565568">0235 356 5568</a><a class="email" href="mailto:maikyhaseafood01@gmail.com">maikyhaseafood01@gmail.com</a><p>Liên hệ trực tiếp hoặc chuẩn bị nội dung hỏi hàng bằng biểu mẫu bên cạnh.</p></aside><form id="inquiry"><noscript><p>Vui lòng bật JavaScript để soạn yêu cầu hoặc gửi email trực tiếp đến <a href="mailto:maikyhaseafood01@gmail.com">maikyhaseafood01@gmail.com</a>.</p></noscript><h2>Chuẩn bị yêu cầu</h2><p class="form-note">Biểu mẫu giúp soạn nội dung email. Bạn sẽ kiểm tra và gửi trong ứng dụng email của mình.</p><div class="two"><label>Họ và tên *<input name="name" required autocomplete="name" maxlength="120"></label><label>Tên doanh nghiệp *<input name="company" required autocomplete="organization" maxlength="160"></label></div><label>Email hoặc số điện thoại *<input name="contact" required maxlength="160"></label><div class="two"><label>Nhu cầu<select name="need"><option value="mua">Tìm mua thủy sản</option><option value="cung-ung">Giới thiệu nguồn hàng</option><option value="khac">Hợp tác khác</option></select></label><label>Sản phẩm<select name="product"><option value="">Chọn mặt hàng / khác</option>{options}</select></label></div><div class="two"><label>Khối lượng dự kiến<input name="quantity" placeholder="Ví dụ: khối lượng và đơn vị" maxlength="120"></label><label>Địa điểm giao<input name="destination" maxlength="180"></label></div><label>Quy cách, thời gian và yêu cầu khác *<textarea name="message" required rows="5" maxlength="2500"></textarea></label><div class="form-actions"><button class="button" type="submit" disabled>Soạn email yêu cầu</button><button class="button secondary" type="button" id="copy-request" disabled>Sao chép nội dung</button></div><p id="form-status" role="status" aria-live="polite"></p><div id="manual-copy" hidden><label>Nội dung để sao chép<textarea readonly rows="8"></textarea></label></div></form></div></section>''')
from english import build_languages
build_languages(D)
from relative_paths import make_relative
make_relative(D)
# One company name everywhere: MAI KỲ HÀ SEAFOOD.
for html_file in D.rglob('*.html'):
 html_file.write_text(re.sub(r'MAI KỲ HÀ(?! SEAFOOD)','MAI KỲ HÀ SEAFOOD',html_file.read_text()))
from seo import build_seo
build_seo(D)
from responsive import add_srcset
add_srcset(D)
# Version CSS/JS links by content so browsers fetch updates right away.
import hashlib
for asset in ('style.css','app.js','logo.png','favicon.png','intro-gate.js'):
 version=hashlib.sha1((A/asset).read_bytes()).hexdigest()[:10]
 for html_file in D.rglob('*.html'):
  text=html_file.read_text()
  html_file.write_text(re.sub(r'(assets/'+re.escape(asset)+r')(\?v=[0-9a-f]+)?"',r'\1?v='+version+'"',text))
print('Generated',len(list(D.rglob('index.html'))),'pages')
